
services:
  data-job:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true #Hält den Container offen
    stdin_open: true # Erlaubt eingaben
    command: tail -f /dev/null
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    environment: 
      - PYTHONUNBUFFERED=1
      - DB_HOST=database                # MÖGLICHER FEHLER???
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
      - TESTCONTAINERS_RYUK_DISABLED=true
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # host:cotainer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
